# Generated by Django 4.0.4 on 2022-06-06 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_courses_teacherprofile_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('number_of_subchapters', models.IntegerField(null=True)),
                ('notes', models.FileField(blank=True, null=True, upload_to='Chapter_notes')),
            ],
        ),
        migrations.CreateModel(
            name='UserCourseMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.courses')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Subchapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('number_of_topics', models.IntegerField(null=True)),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.chapters')),
            ],
        ),
        migrations.AddField(
            model_name='chapters',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.subjects'),
        ),
    ]
