# Generated by Django 4.0.4 on 2022-06-12 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_transactions_topicscovered_liveclasses_gyan_coupons_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressReportSubChap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_attempts', models.IntegerField(null=True)),
                ('highest_attempt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SubChapter_progress_highest_attempt', to='users.scoretable')),
                ('latest_attempt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SubChapter_progress_latest_attempt', to='users.scoretable')),
                ('lowest_attempt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.scoretable')),
                ('sub_chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.subchapters')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressReportChap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_attempts', models.IntegerField(null=True)),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.chapters')),
                ('highest_attempt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Chapter_progress_highest_attempt', to='users.scoretable')),
                ('latest_attempt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Chapter_progress_latest_attempt', to='users.scoretable')),
                ('lowest_attempt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.scoretable')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
