# Generated by Django 4.0.4 on 2022-06-12 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_progressreportsubchap_progressreportchap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapternotes',
            name='file_url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('thumbnailUrl', models.CharField(max_length=50, null=True)),
                ('video', models.URLField(blank=True, null=True)),
                ('sub_chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.subchapters')),
            ],
        ),
        migrations.AlterField(
            model_name='questions',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.topics'),
        ),
        migrations.AlterField(
            model_name='topicscovered',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.topics'),
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
