# Generated by Django 4.0.4 on 2022-06-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_chapternotes_file_url_topics_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topics',
            old_name='sub_chapter',
            new_name='subchapter',
        ),
        migrations.AlterField(
            model_name='topics',
            name='thumbnailUrl',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
